function Q = integration(freq, pressure)
min_press = min(pressure)
result = find(pressure == min_press)
char_freq = freq(result)
pascal = 2.*10.^(-5).*10.^(pressure./20)
min_pascal = 2*10^(-5)*10^(min_press/20)
flipped = (min_pascal./pascal)
bandwidth = trapz(freq, flipped)
figure(1)
plot(freq,pascal)
xlabel("frequency")
ylabel("pressure in Pascal")
title("curve of pressure in Pascal against frequency")
figure(2)
plot(freq, pressure)
xlabel("frequency")
ylabel("pressure in dB")
title("curve of pressure in dB against frequency")
figure(3)
plot(freq, flipped)
xlabel("frequency")
ylabel("pressure in Pascal")
title("flipped normalised curve")
Q = char_freq/bandwidth

